import matplotlib.pyplot as plt
import numpy as np

#tvals = np.loadtxt('tvals1.csv', delimiter=',')
#for i in range(1,16):
#    tvals = tvals + np.loadtxt('tvals' + str(i) + '.csv', delimiter=',')
#print(len(np.arange(10,2920,10)))
#print(len(tvals))
#fig, _ = plt.subplots()
#fig.patch.set_facecolor((0.8,0.9999*0.85, 0.9))
#plt.plot(np.arange(10,2920,10),tvals/15)
#ax = plt.gca()
#ax.set_xlabel('Number of Subjects')
#ax.set_ylabel('Time (seconds)')
#ax.set_xlim([0,2910])
#ax.grid(True)
#np.savetxt('tvals_total_ns.csv', tvals/15)
#print(130*56)
#plt.show()

tvals = np.loadtxt('tvalsmem_total_ns.csv', delimiter=',')
print(len(tvals))
fig, _ = plt.subplots()
fig.patch.set_facecolor((0.8,0.9999*0.85, 0.9))
plt.plot(np.arange(28,36.5, 0.5),tvals/15)
ax = plt.gca()
ax.set_xlabel('log(Maximum Memory) (bits)')
ax.set_ylabel('Time (seconds)')
ax.set_xlim([27.5,36.5])
ax.set_ylim([0,3600])
ax.grid(True)
np.savetxt('tvalsmem_total_ns.csv', tvals*10)
print(130*56)
print(tvals)
plt.show()
